# Generated by Django 5.0.6 on 2024-08-05 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalBreed",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("animal_breed", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Animalcolor",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("animal_color", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("animal_views", models.IntegerField(default=0)),
                ("animal_likes", models.IntegerField(default=1)),
                ("animal_name", models.CharField(max_length=100)),
                ("animal_description", models.TextField()),
                ("animal_slug", models.SlugField(max_length=1000, unique=True)),
                (
                    "animal_gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=50
                    ),
                ),
                (
                    "animal_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "animal_breed",
                    models.ManyToManyField(blank=True, to="home.animalbreed"),
                ),
                (
                    "animal_color",
                    models.ManyToManyField(blank=True, to="home.animalcolor"),
                ),
                (
                    "animal_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="home.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-animal_name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalImages",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("animal_images", models.ImageField(upload_to="animals")),
                (
                    "animal_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.animal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnimalLocation",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("56f4f1d2-b70c-4160-bfdf-44b5ccfc2467"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "animal_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="home.animal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
