# Generated by Django 5.0.6 on 2024-08-06 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animalbreed",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animalcolor",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animalimages",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="animallocation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("964288d2-3396-464a-98f7-9e1b903b830e"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
